language: node_js
node_js:
- lts/*
script:
- echo "n/a"
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx @dhis2/cli-utils release --publish npm
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: kRoGuVs1zMkoYmo9QVU9HFmGFSLetjuM/K32fx3+P4GYJrNRIo9cuz9Fx7mJfkVEJOy1xLf/RiVkTYCPMoeRHUGr/hMTgP9s1z3m0EigIge5sSCgkHc6LDOYP/Ha3mJS+FsGEYeVgep1a6G3O/oRP+0O0hWn2liON2DUd0PnEwSXjmJGZIoDFYeU7ChmopKfQXXxkfpWfKPwmylLfVAWT/MPUmrKDfrCWpnSzZjNdh+s3m1B5iKkIk0gbuo/mFq7dDlLTJ6Gy4T5DOuGk4vl0PVY2n+ayj/z+ZRYATeMMGTj9JRT9QKdiyN8Z/2jkPJI82wqOvtdiyS4W/D9Sk18XbZEtzAcpKK6pEypoj+PE2A0nHjDOLFppFPC1MhOxxB34q+8aNOj1bkDQbTQj5G64pTkznj6nA9abVNBbjpjkEbwBGnZLVsFpoRhjlLnVPHNfZdC+EZtYcdh8iZ7S2UfMtndYXj2/NNWrSrxEy1gOWsSTFWI4NRk2yp7j1AVtFBF0Q4zHZJ4fxQ8u253/leWhDE6ZKmKElJFCR4UGQszb7CZIcLnIhWRIksFf7Zi+q40A5Zb7o9ciNdyC42mpJdFUPveY08fQtwIE7srO4qxVWyd3oBL91qmN/Cp/F6JaS8aiT5ZuZs0NTjokkWaKHQwSR6lySWfiepC3WBxYsgSa2U=
  - secure: YnVQ1dRWIqMowg/zjSLPXtLJiT6lb5qz+KahVPDQ7Dx3pTva1JKSVraVrZdvd3EcnZKnTuzZqPwcAndLnUuuuTJl9ZRF+O9KZNjcWVZRD8fvGZjuJByu8GCHogiEYxuDqbwyeHKa7kSWTOojkK1cfVTGTi2dYd4UzxFdUV4O9ISD8d6nSNMQjuv34b/Bg0ObeFO63EgMYpB8cN4SUtNcczU0GofEfXHUtyTXBnLMP7ip+k91ij/zXj9tavyIEfsxHU75VuVqd406I8dYlfsgAMHfnk4nQYgx2y6pAPtDtMDf0mnbqcrSo26XYlKUuW/1WE6p6LS3g/c/gJlGhEx88F5YrHlzK2wvKfCmDNfr2ERSi1euaLe/cDEY07hb46/FOo+xzVGzxqtAiPflOIFfiJi3FrWjH3Assd6+UyNvv9z8H1geGZZxOk0GlGibz8L/PWPPY1jiv+VcjbPtORZt1QbJaKXKUy1CfqWPhsLeP3b67RsRfjJt3nxwCjffevkB0vTZqgN7E5eDDLagv8fdErgYJh380Nnb4GKltUOaAhSWaWSlQiOomhSmU0ljScgrx+7g3gaE6DDH0/imDPa4tqVyUHe2USkNmM9xitn2e+/6n+1z/mNRhR943lnlQwexgmG2Kp2Mk5wdhA3QHHvoY1QPVhyGbBZlzOKmw2tkGBY=
